### ISSUE TITLE
installed on OSX mavericks using zsh and can't seem to get it to work - it's definitely not in my $PATH

### ISSUE THREAD

**Issue by dstroot** [andrewrk/swig-email-templates#16]
Even this is crapping out and yes, there is a welcome.html in /templates:

```
› node_modules/swig-email-templates/bin/swig-email-templates.js render welcome.html

fs.js:427
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT, no such file or directory 'welcome.html'
    at Object.fs.openSync (fs.js:427:18)
    at Object.fs.readFileSync (fs.js:284:15)
    at /Users/Dan/Code/node-html-emails/node_modules/swig-email-templates/bin/swig-email-templates.js:112:16
    at Array.forEach (native)
    at Object.<anonymous> (/Users/Dan/Code/node-html-emails/node_modules/swig-email-templates/bin/swig-email-templates.js:111:8)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
```

**Comment by takkaria** [comment]
Closing this issue because it's been inactive for a long time.  Please re-open if this continues to be a problem.
