### ISSUE TITLE
Breaks on node/iojs > v0.11.13, TypeError: Cannot read property 'removeChild' of nul

### ISSUE THREAD

**Issue by naartjie** [andrewrk/swig-email-templates#25]
I'm getting a `TypeError: Cannot read property 'removeChild' of null`, for something which used to work on `node v0.11.13`, and is broken on any node or iojs version after that:

```shell
TypeError: Cannot read property 'removeChild' of null
  at removeStyleTags (server/node_modules/swig-email-templates/node_modules/juice2/lib/juice.js:272:32)
  at getStylesData (server/node_modules/swig-email-templates/node_modules/juice2/lib/juice.js:294:3)
  at /Users/marchi/Project/Swarm/loyalty-server/node_modules/swig-email-templates/node_modules/juice2/lib/juice.js:356:5
```

This looks related to andrewrk/juice#16.

**Comment by naartjie** [comment]
Just to clarify, this is broken on node `v0.12.0` and `v0.12.1`.

**Comment by laurynas-karvelis** [comment]
+1

**Comment by michelem09** [comment]
latest version with 0.12.x works fine

**Comment by naartjie** [comment]
thanks @michelem09
