### ISSUE TITLE
Cannot set property 'useTemplate' of undefined

### ISSUE THREAD

**Issue by prasad47** [andrewrk/swig-email-templates#42]
hi,
Code :- 

```

var path = require('path'),
    emailTemplates = require('swig-email-templates'),
    _ = require('lodash');

var options = {
    root: path.join(__dirname, '../templates')
    // any other swig options allowed here
};
console.log('-------------------------------------------options'+JSON.stringify(options));

exports.orderConfirm=function(order,callback){
    emailTemplates(options, function(err, render) { Line 42
        render('email/order-confirm.html', order, function(err, html) {
            callback(html);
        });
    });
};
```
Following Error Happening : -

```
------------------------------------------options{"root":"/app/templates"}  precise as per the Folder structure ..

TypeError: Cannot set property 'useTemplate' of undefined 
  at EmailTemplates (/app/node_modules/swig-email-templates/index.js:32:20)
at Object.exports.orderConfirm(/app/app/controllers/emailTemplates.server.controller.js:42:5)  

```

Could You Guys Suggest i am stuck  with out clue :-( 

Thanks,
Prasad

**Comment by prasad47** [comment]
any one have seen it guys ... ????

**Comment by takkaria** [comment]
What version of node are you using?

**Comment by takkaria** [comment]
Also, it looks like you are not using the most up to date version of the library.  Please try upgrading, and [see the README](https://github.com/andrewrk/swig-email-templates#quick-start) about the right way to use it now.
